spring:
  datasource:
    druid:
      url: jdbc:mysql://192.168.1.102:3306/bookstoredatabase?useUnicode=true&characterEncoding=gbk&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      username: root
      password: 1234
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    static-path-pattern: /img/**

  resources:
    static-locations: file:D:\WorkSpace\test\book-store\webapp\upload

mybatis:
  type-aliases-package: com.eins.book.store.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8080
